## Joins in pandas

common attributes kai base pr dta

In [6]:
import pandas as pd

data = pd.read_excel("test_data.xlsx")

data

   sales_man_id sales_man_name sales_man_city  product_id  manager
0             1          nasir        Karachi         123    jawed
1             2         furqan        lahore          123    jawed
2             3          usman        lahore          345    jawed
3             4          ahmed        karachi         556    najam
4             5         rehman         jhelum         445  shafeeq
5             6          talha      islamabad         556      ali
6             7        huzaifa        karachi         233    najam
7             8         rehman        karachi         778      ali
8             9          akram      islamabad         775  shafeeq

In [16]:
data1 = pd.read_excel("modify.xlsx")

data1

  sales_man_name region  Sales   Amount
0           Asad      A    200   100000
1         rehman      B    220   450000
2        hussain      C    332   125000
3           sana      D    220   652000
4         fatima      E    500   145000
5         kashif      F    321   852000
6   hasan rahman      G    510   125000
7      ab rehman      H    350  3250000
8          ahmed      I    250    86026

In [17]:
pd.merge(data , data1)

,sales_man_id,sales_man_name,sales_man_city,product_id,manager,region,Sales,Amount
0,4,ahmed,karachi,556,najam,I,250,86026
1,5,rehman,jhelum,445,shafeeq,B,220,450000
2,8,rehman,karachi,778,ali,B,220,450000