## Computing indicators / Dummy Variables

# numerical =  2 , 1 , 3 , 4

# categorical data = manager , male , female , yes , no

## categorical ---- ordinal ---- nomimal

### Nominal data 

Examples:

Blood Group: A, B, AB, O
Gender: Male, Female
Eye Color: Brown, Blue, Black
City: Karachi, Lahore, Islamabad

You cannot say:

Karachi > Lahore ❌
Blue > Brown ❌

There is no meaningful order.


### Ordinal data


Examples:

Education: High School → Bachelor's → Master's → PhD
Satisfaction: Very Dissatisfied → Dissatisfied → Neutral → Satisfied → Very Satisfied
T-Shirt Size: Small → Medium → Large → XL
Movie Rating: 1 Star → 2 Stars → 3 Stars → 4 Stars → 5 Stars
Grades: A+ → A → B+ → B → C → D

You know:

Large > Medium > Small ✅

But you don't know how much larger one category is than another.

In [1]:
import pandas as pd

data = pd.read_excel("employee.xlsx")

# One Hot Encoding 


Example 2: Gender

Original Data:

Gender
Male
Female
Male

After One-Hot Encoding:

        Male	Female
Male     1	      0
Female   0	      1
Male     1	      0

In [3]:
pd.get_dummies(data.Designation)

    Accountant  Engineer  Manager  Office Boy  Officer
0        False     False     True       False    False
1        False     False    False       False     True
2        False     False    False       False     True
3        False     False     True       False    False
4        False     False    False        True    False
5         True     False    False       False    False
6         True     False    False       False    False
7        False     False    False       False     True
8        False     False     True       False    False
9        False      True    False       False    False
10       False     False    False       False     True
11        True     False    False       False    False
12       False      True    False       False    False
13       False     False    False       False     True
14       False     False    False       False     True
15       False     False    False       False     True
16       False      True    False       False    False
17       False     False    False        True    False
18       False      True    False       False    False
19       False     False    False       False     True
20        True     False    False       False    False
21        True     False    False       False    False
22       False      True    False       False    False
23       False     False    False       False     True

In [4]:
pd.get_dummies(data)

,Serial,Emp_ID,Age,Salary,Designation_Accountant,Designation_Engineer,Designation_Manager,Designation_Office Boy,Designation_Officer,Department_Account,Department_Accounts,Department_HR,Department_IT,Department_Production
0,1,1101,50.0,200000.0,False,False,True,False,False,False,True,False,False,False
1,2,1107,30.0,80000.0,False,False,False,False,True,False,False,False,True,False
2,3,1203,28.0,NaN,False,False,False,False,True,False,False,True,False,False
3,4,1005,45.0,120000.0,False,False,True,False,False,False,False,True,False,False
4,5,2123,27.0,45000.0,False,False,False,True,False,False,True,False,False,False
5,6,2451,34.0,100000.0,True,False,False,False,False,False,False,False,False,False
6,7,1111,NaN,110000.0,True,False,False,False,False,False,True,False,False,False
7,8,1001,25.0,75000.0,False,False,False,False,True,False,False,False,True,False
8,9,1234,23.0,NaN,False,False,True,False,False,False,False,False,True,False
9,10,2156,45.0,89000.0,False,True,False,False,False,False,False,False,False,True
10,11,6543,29.0,100000.0,False,False,False,False,True,False,False,False,False,True
11,12,3214,49.0,123000.0,True,False,False,False,False,True,False,False,False,False
12,13,2156,45.0,89000.0,False,True,False,False,False,False,False,False,False,True
13,14,1098,25.0,100000.0,False,False,False,False,True,False,False,False,True,False
14,15,2912,31.0,90000.0,False,False,False,False,True,False,False,False,True,False
15,16,1222,25.0,NaN,False,False,False,False,True,False,False,False,False,False
16,17,2156,45.0,89000.0,False,True,False,False,False,False,False,False,False,True
17,18,2123,27.0,45000.0,False,False,False,True,False,False,True,False,False,False
18,19,2156,45.0,89000.0,False,True,False,False,False,False,False,False,False,True
19,20,6543,29.0,100000.0,False,False,False,False,True,False,False,False,False,True
20,21,3214,49.0,123000.0,True,False,False,False,False,True,False,False,False,False
21,22,3214,49.0,123000.0,True,False,False,False,False,True,False,False,False,False
22,23,2156,45.0,89000.0,False,True,False,False,False,False,False,False,False,True
23,24,1098,25.0,100000.0,False,False,False,False,True,False,False,False,True,False